# Event Horizon - Futuristic Event Management Platform
# Copyright (C) 2025-2026 Arnav Ghosh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
Django settings for EventHorizon project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG := os.getenv("DEBUG", "False").lower() in {"true", "1", "yes"}:
        SECRET_KEY = (
            "N_xsGTkMKK9BYha6hGCYJgoIIMP0WRMZT5IGHN8oESql1L1yqNLdX8GxEmT9god1ops"
        )
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable must be set in production"
        )
else:
    DEBUG = os.getenv("DEBUG", "False").lower() in {"true", "1", "yes"}

# Parse ALLOWED_HOSTS from environment
allowed_hosts_str = os.getenv("ALLOWED_HOSTS", "")

if allowed_hosts_str == "*":
    # Handle wildcard - allow all hosts (development/testing)
    ALLOWED_HOSTS = ["*"]
else:
    # Parse comma-separated list
    ALLOWED_HOSTS = [
        host.strip() for host in allowed_hosts_str.split(",") if host.strip()
    ]

# Auto-detect Vercel deployment
if os.getenv("VERCEL"):
    vercel_url = os.getenv("VERCEL_URL")
    if vercel_url and vercel_url not in ALLOWED_HOSTS and "*" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(vercel_url)
    # Allow all Vercel preview/production deployments
    if ".vercel.app" not in ALLOWED_HOSTS and "*" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(".vercel.app")

if DEBUG:
    ALLOWED_HOSTS = ALLOWED_HOSTS or ["127.0.0.1", "localhost", "0.0.0.0"]
else:
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set when DEBUG is False")


# Security Settings
# https://docs.djangoproject.com/en/6.0/topics/security/

# HTTPS/SSL Settings (enabled in production when DEBUG=False)
if not DEBUG:
    # Redirect all HTTP requests to HTTPS
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in {
        "true",
        "1",
        "yes",
    }

    # HSTS (HTTP Strict Transport Security)
    # Forces browsers to use HTTPS for this site for the specified duration
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", "True"
    ).lower() in {"true", "1", "yes"}
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "True").lower() in {
        "true",
        "1",
        "yes",
    }

    # Cookie Security
    SESSION_COOKIE_SECURE = True  # Only send session cookie over HTTPS
    CSRF_COOKIE_SECURE = True  # Only send CSRF cookie over HTTPS

    # Additional Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
else:
    # Development mode - disable SSL requirements
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    # Plugins
    "oauth2_provider",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "rest_framework",
    "knox",
    "corsheaders",
    # Local Apps
    "events",
    "users",
    "home",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "knox.auth.TokenAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

# Caching configuration
# - Defaults to in-memory cache (safe everywhere)
# - If REDIS_URL is provided, uses Redis via django-redis
REDIS_URL = os.getenv("REDIS_URL")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "eventhorizon-locmem",
        }
    }

# Knox token settings
# Default: 12 hours (user can override per token)
REST_KNOX = {
    "TOKEN_TTL": timedelta(hours=12),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files efficiently
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

# CORS configuration - Open by default to support third-party OAuth clients
# EventHorizon is designed as a platform for community developers to build against
# APIs are protected by OAuth2/Token auth, so CORS can be permissive
# For production lockdown, set CORS_ALLOW_ALL_ORIGINS=false and specify CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True").lower() in {
    "true",
    "1",
    "yes",
}

if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
        if origin.strip()
    ]
    if not CORS_ALLOWED_ORIGINS:
        # Fallback for local development if explicitly disabled
        CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]

ROOT_URLCONF = "EventHorizon.urls"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
                "EventHorizon.context_processors.seo_context",
            ],
        },
    },
]

WSGI_APPLICATION = "EventHorizon.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use DATABASE_URL environment variable if provided, otherwise fall back to SQLite
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Parse the DATABASE_URL connection string
    # Supports: postgresql://, mysql://, sqlite:///
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,  # Connection pooling for better performance
            conn_health_checks=True,  # Enable connection health checks
        )
    }
else:
    # Default to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Storage Configuration
# For Vercel/serverless: Use S3 for static files (no filesystem access)
# For traditional servers: Use WhiteNoise (efficient, cached)

if os.getenv("VERCEL") or os.getenv("USE_S3_FOR_STATIC", "False").lower() in {
    "true",
    "1",
    "yes",
}:
    # Vercel/Serverless: Must use S3 for static files
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "storage.s3.S3StaticStorage",
        },
    }
else:
    # Traditional server: Use WhiteNoise for efficient static file serving
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Email Configuration
if os.getenv("EMAIL_BACKEND") == "smtp":
    # Production SMTP configuration
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {"true", "1", "yes"}
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in {"true", "1", "yes"}
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
    SERVER_EMAIL = os.getenv("SERVER_EMAIL", EMAIL_HOST_USER)
elif os.getenv("EMAIL_BACKEND") == "sendgrid":
    # SendGrid API configuration
    EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
    SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")
    SENDGRID_SANDBOX_MODE_IN_DEBUG = False
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@eventhorizon.local")
    SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
elif os.getenv("EMAIL_BACKEND") == "mailgun":
    # Mailgun configuration
    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
    ANYMAIL = {
        "MAILGUN_API_KEY": os.getenv("MAILGUN_API_KEY", ""),
        "MAILGUN_SENDER_DOMAIN": os.getenv("MAILGUN_SENDER_DOMAIN", ""),
    }
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@eventhorizon.local")
    SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
else:
    # Development: Console backend (prints emails to terminal)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "noreply@eventhorizon.local"
    SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Django Allauth Configuration
# Email is required for registration
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
LOGIN_REDIRECT_URL = "profile"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

# Custom Account Adapter (auto-verifies staff/superuser emails)
ACCOUNT_ADAPTER = "users.adapters.account.CustomAccountAdapter"

# Email Verification Settings
ACCOUNT_EMAIL_REQUIRED = True  # Email is required for signup
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Options: "none", "optional", "mandatory"
ACCOUNT_AUTHENTICATION_METHOD = "username_email"  # Allow login with username or email
ACCOUNT_USERNAME_REQUIRED = True  # Username is required
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Verification link expires after 3 days
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Auto-login after email verification

# NOTE: Staff and superuser accounts are exempted from email verification
# via CustomAccountAdapter. Their emails are auto-verified on signup/login.

# Social Account Settings
SOCIALACCOUNT_EMAIL_VERIFICATION = (
    "optional"  # Don't require verification for social logins
)
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto-create account from social login
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from social providers

OAUTH2_PROVIDER = {
    # this is the list of available scopes
    "SCOPES": {
        "read": "Read scope",
        "write": "Write scope",
        "groups": "Access to your groups",
        "openid": "OpenID Connect scope",
    },
    "OIDC_ENABLED": True,
    "OIDC_RSA_PRIVATE_KEY": os.getenv("OIDC_RSA_PRIVATE_KEY"),
    "OIDC_ISS_ENDPOINT": "http://127.0.0.1:8000/o",
    "CLIENT_SECRET_HASHER": "plain",
}


# Storage Configuration
# Choose storage backend: local (default), s3, minio
STORAGE_BACKEND = os.getenv("STORAGE_BACKEND", "local").lower()

if STORAGE_BACKEND in ["s3", "minio"]:
    # S3-Compatible Storage (AWS S3, MinIO, DigitalOcean Spaces, Cloudflare R2)
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")

    # For MinIO or other S3-compatible services, set a custom endpoint
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")

    # SSL Configuration (use False for local MinIO without SSL)
    AWS_S3_USE_SSL = os.getenv("AWS_S3_USE_SSL", "True").lower() in {"true", "1", "yes"}

    # Custom domain for CDN (optional)
    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN")

    # Signature version (use 's3v4' for newer AWS regions)
    AWS_S3_SIGNATURE_VERSION = os.getenv("AWS_S3_SIGNATURE_VERSION", "s3v4")

    # File handling
    AWS_S3_FILE_OVERWRITE = False  # Don't overwrite files with same name
    AWS_DEFAULT_ACL = "public-read"  # Make uploaded files publicly accessible
    AWS_QUERYSTRING_AUTH = False  # Don't add auth query params to public URLs

    # Django 4.2+ Storage configuration
    STORAGES = {
        "default": {
            "BACKEND": "storage.s3.S3MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    # Use S3 for static files if on Vercel or explicitly enabled
    if os.getenv("VERCEL") or os.getenv("USE_S3_FOR_STATIC", "False").lower() in {
        "true",
        "1",
        "yes",
    }:
        STORAGES["staticfiles"]["BACKEND"] = "storage.s3.S3StaticStorage"

    # Construct media URL
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    elif AWS_S3_ENDPOINT_URL:
        # For MinIO or custom endpoints
        endpoint = AWS_S3_ENDPOINT_URL.rstrip("/")
        MEDIA_URL = f"{endpoint}/{AWS_STORAGE_BUCKET_NAME}/media/"
    else:
        # Standard AWS S3 URL
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/"

    # Construct static URL (for Vercel/S3 static serving)
    if os.getenv("VERCEL") or os.getenv("USE_S3_FOR_STATIC", "False").lower() in {
        "true",
        "1",
        "yes",
    }:
        if AWS_S3_CUSTOM_DOMAIN:
            STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
        elif AWS_S3_ENDPOINT_URL:
            endpoint = AWS_S3_ENDPOINT_URL.rstrip("/")
            STATIC_URL = f"{endpoint}/{AWS_STORAGE_BUCKET_NAME}/static/"
        else:
            STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/static/"
else:
    # Local filesystem storage (default for development)
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    MEDIA_URL = "/media/"
