# Generated by Django 6.0 on 2025-12-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='registration',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
