# Generated by Django 6.0 on 2025-12-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_registration_schema_registration_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to receive JSON notifications on new registrations', null=True),
        ),
    ]
