# Generated by Django 6.0 on 2025-12-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_webhook_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='webhook_url',
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to receive JSON notifications')),
                ('secret', models.CharField(blank=True, help_text='Secret for signature verification', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='events.event')),
            ],
        ),
    ]
