# Generated by Django 6.0 on 2025-12-29 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_webhook_url_webhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='events_even_organiz_266ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created_at'], name='events_even_created_7af6de_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'status'], name='events_regi_event_i_c98244_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['participant'], name='events_regi_partici_cf60c9_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['-registered_at'], name='events_regi_registe_144b1f_idx'),
        ),
    ]
